name: Sync from upstream repository

on:
  schedule:
    - cron: '0 0 * * *'  # 每天同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "evilhy"
          git config user.email "1422409065@qq.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/dler-io/Rules.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git merge upstream/main || true

      - name: Check for workflow changes
        id: check
        run: |
          if git diff --name-only HEAD~1 | grep '^.github/workflows/'; then
            echo "Workflow files changed. Skipping push."
            echo "skip_push=true" >> $GITHUB_OUTPUT
          else
            echo "No workflow changes. Proceeding to push."
            echo "skip_push=false" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        if: steps.check.outputs.skip_push == 'false'
        run: |
          git push origin main
