name: Sync from upstream repository

on:
  schedule:
    - cron: '0 0 * * *'  # 每天同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "evilhy"
          git config user.email "1422409065@qq.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/dler-io/Rules.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git merge upstream/main || true

      - name: Revert workflow file changes
        run: |
          # 恢复 workflows 目录为 merge 前状态（保留本地版本）
          git restore --staged .github/workflows || true
          git restore .github/workflows || true

          # 若你不需要保留 workflows，可直接清空它：
          # rm -rf .github/workflows
          # git add -u .github/workflows

          git status  # 查看剩余变更

      - name: Commit and push (excluding workflows)
        run: |
          git commit -am "sync: update from upstream (excluding workflows)" || echo "No changes to commit"
          git push origin main
          
      # - name: Check for workflow changes
      #   id: check
      #   run: |
      #     if git diff --name-only HEAD~1 | grep '^.github/workflows/'; then
      #       echo "Workflow files changed. Skipping push."
      #       echo "skip_push=true" >> $GITHUB_OUTPUT
      #     else
      #       echo "No workflow changes. Proceeding to push."
      #       echo "skip_push=false" >> $GITHUB_OUTPUT
      #     fi

      # - name: Push changes
      #   if: steps.check.outputs.skip_push == 'false'
      #   run: |
      #     git push origin main
